### PR TITLE
Add/themes

### PR DESCRIPTION
**Pull request by nosolosw**
This PR aims to make the happychat-client library themable, addresing https://github.com/Automattic/happychat-client/issues/141

The first step is having a Woo theme in addition to the default / WordPress.com one. For reference, here's the [Woo style guide](https://woocommerce.com/style-guide/#sg-palette).

### CODE REVIEW

**Comment by nosolosw** [comment]
@kellychoffman I've changed the main color from `$blue-medium` (`#00aadc`) to purple (`#96588a`) and tried to capture most of the potential UI states in the following screenshots. There's still tons of blues and grays that adapt well to the WordPress.com / Calypso color palette but don't quite fit the woo one.

In case it's useful, the current color palette is defined [here](https://github.com/Automattic/happychat-client/blob/master/src/ui/css/shared/_colors.scss) (it's the same than Calypso).

### Contact form

Main view:

form-2018 03 28 18-23-51

Item list detail:

item-list-2018-03-28-18-38

### Chat form 

Ongoing chat: 

chat-2018 03 28 18-25-14

Chat not available:

chat-disabled-2018-03-28-18-37

Perhaps the next major step could be to tweak the omnipresent `$blue-light` (`#78dcfa`) to some kind of purple-light?

**Comment by rickybanister** [comment]
This is awesome! For Jetpack.com we would want the 'call out' color to be #00be28 and everything else can stay the default Calypso colors since Jetpack.com has been made more in line with the calypso styleguide. 

cc @jeffgolenski who is our keeper of brand and marketing stuff if you need further advice!

**Comment by kellychoffman** [comment]
Nice! Can we just add purple to the active inputs and text ::selection? 

I would also like to test this on a staging site before we push anything live to Woo make sure there's nothing else I missed, but overall, this is looking good.

**Comment by nosolosw** [comment]
It seems that by reorganizing the colors in the codebase around accents and neutrals (without using specific color names such as blue, gray, etc) it's clearer what colors new themes need to declare and for what purpose. Added some [docs](https://github.com/Automattic/happychat-client/pull/187/files#diff-829b7582446bc85ddf176d4d62ecc502).

After doing that, I've gone ahead and -in the woo theme- I've changed the gray-blueish with some woo gray so it looks better. For Jetpack, the only change was to use `#00be28` as the accent, and the neutrals were reused from the default/WordPress.com ones.

Click on the images for the details.

**Contact Form**

WordPress.com | Jetpack | WooCommerce 
--- | --- | ---
form-2018-03-31-20-16-44-wp | form-2018-03-31-20-18-26-jpop | form-2018-04-01-12-36-34-woo

**Item list**

WordPress.com | Jetpack | WooCommerce 
--- | --- | ---
item-list-2018-03-31-20-17-04-wp | item-list-2018-03-31-20-18-41-jpop | item-list-2018-04-01-12-36-54-woo

**Chat form**

WordPress.com | Jetpack | WooCommerce 
--- | --- | ---
chat-2018-03-31-18-45-43-wp | chat-2018-03-31-18-44-51-jpop | chat-2018-03-31-20-29-14-woo

**Chat disabled with notices**

WordPress.com | Jetpack | WooCommerce 
--- | --- | ---
chat-disabled-2018-03-31-20-31-52-wp | chat-disabled-2018-03-31-20-30-22-jpop | chat-disabled-2018-03-31-20-27-41-woo

As I'm starting my AFK on Tuesday 4th, I'd like to merge this and then iterate to refine anything we want later. Let me know what you think @kellychoffman @evilluendas @rickybanister 

As the CSS is shipped from WordPress.com CDN, before I update Woo staging demo page with these changes I need to update WordPress.com with the proper CSS. When that's ready, this can be merged and so the demo in staging.

**Comment by nosolosw** [comment]
Going to merge this to sync with the WordPress.com CDN deploy and update the demo. That'll make easy to spot any issues that we fix and iterate further in separate PRs.

**Comment by dwainm** [comment]
🎉

**Comment by rickybanister** [comment]
I think this looks good for now!

cc @jeffgolenski when you're back from your conference, can you take a look. I'd love for us to get away with just one shade of green, but I'm scared that we need a darker one for any text vs other accents.

**Pull request merged**
